# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:  master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk


  firebase:
    name: Run UI tests with Firebase Test Lab
    needs: apk
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Download Android test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: test2-74b82
          service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGVzdDItNzRiODIiLAogICJwcml2YXRlX2tleV9pZCI6ICI2YWJkNDg5YjcyNjY0MGRlZGYyMGUwOWE5MTcyYTAzNjY5YTNlMGUyIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUNYTGpsNFU2ZlRhZ1N1XG5vbjhwak9oa2hKNncyaFpUOVhyZDh3Qmc2dmovdE00bEZtM3ZUWFcyS2MzcmFQaHFxdUlaSmtBU2w2OFg0YjZuXG5NUGJoU1FPb0Ird05VUEdTcGNENTB2blVIUDFvNU0zbFRvclB0WmpKU3VXWUlKejR1ZVhhN2FsRXBFS2NIb3NzXG5MM0t4d3JIMHBjTXZqOHhvcU1Zek1FL09ReGFMSG1SSms3Q01jbThLMENVQ3RWeVlpSDhkVkNkL3Y0aWI2Kys2XG5Xdk9BTlJhRVBJajUvMVpEeEZCUUxXdGZjTmtsRWljcCtNTHJVenBETnNRSFFUSnVyQ1VIbjB1OTZVN1g5UmUwXG5wRlBSUFhMaUEwTm5HWG5wMWxnUmVJcTl1OGpMSXZsTXJOcFU3S0NkZ2VZYnhxMVd3VXFLVGR6MENmSmtCejdCXG5VVGdGeUpqWEFnTUJBQUVDZ2dFQVNxRnlsSEJ6c2wydFp3cG56UHEzQkZ3bHZMZEVlM2o5Q1JFN09CejNBOEJkXG5YWmluZDVGZEVTcXM4VS8yQmk1S2hGREtJNE9HMTdyRXMrTnJsSVpIVEUxdzNaZitVVDhMTnlqTDFNYms0RUhIXG5WTEpEdTByeDNEamhnNHBpQXpVOS82Z0FQaGI2blBoRkN2QjNaY0p2dUE2V2Z1VzFhbHNhME0xQ01GZ1ZDbUtaXG5YQXdBVzI2aEFTVzczenY3a2RPWmtPNDVqZXJ1c2VQck1HcWRhc2lTaE9Tb3FSdXhyQ2lUV0ZCeSs3ZUt4VHpOXG5mQVh5ajRDbm0yTkd1TmdKQnVsWWdCNnlPckRTcE1rQ3pwSTRtVmwwdXNuc1g0bFY4WURjNnJhQTlGS2JXeUFzXG5QVC8zblZUeDVDc1ZGMHFtZVNrWGNqWmcrTTE4bzZnVDArMGxTem1IUlFLQmdRRFFyRGNkM3A3bmNnajhBelBYXG5hYWJqWHZjL2QwUy9vQnZqYkdaSFNDOENHYmM2bCtjVmx3ckhJdWZvNlR3ZjlkWGFSK2RibVVGbTd6T3IyaldNXG5WRTJGSUptbFpyT3BBam5ueWthSHgwblp1WHJBOTgyRCs5Ui9YbUphNXpFYXJBYXdIYkhST3lvMnBuTzZRdk9lXG5IVnF3Y2RlNFVONjRhT1VIck1YK0o5YjJGUUtCZ1FDNWQvSm1PS1V0UWZucXVHa0hFZU1tK0Q0MWFtS2ZVdStoXG5xeUtJYXdPZTArTDZWOEg5RjZRWmxrSzUxSnNhaTdoZUxJdEwwK3pyVHNSTkg2MitpY3VUdjZOcHdjWjNRbE5pXG55Rkk2SkRhODhUT1hkYUFXREplRHNnRFVMRllONzZzNmRWWUFxTUo4d2RSeTlPZTZ5clFqa3grcWpvVkliYjdTXG5lUFE0UHZEYU93S0JnRC9PNld1d3oxWm1nR2pQY2VMRTQ4dFRGcmZKZUxRLytVY3B0bnpGamRwT2tzRFFBbEdQXG54alB1Y0l2QUJpcWZ1YXp0bjhsYXE2MFdKKzY4NHZMdU5HWW8rZEtoL1A0Sk9EdXdsckNlTis3ajBLMkJHTTdyXG5DcWVIN1B0dkJvenBYWUl0RWxxd2hOQUJSaElHdHdmNlllamladHh0bmkwMXBoTWF1ZEJsemsyaEFvR0JBSWZKXG54OUVMZS9PTXNGc25OTTRXVEliRmpWWXlVNDV1ZkQrVE9pOUNtbDM0cDkrOXpLdHVXWmphS0hSQnNtVlhFbDd3XG5vZk9jYjROQUlmeU5Tdm1MalY3WkdkMWVIOTVFMHlRcG9mb3JkV0FVQUQvTndLMGovdkpPcXNpc3hUeGkwcXgwXG5KOGxIeFV6dDVJdGR2eU5GTVdveVZ5YmFQYjd2aXB3eUxpdlgrU0x0QW9HQkFMNVY5L29zaXpnVWZHaWpXcXAxXG40MlU0U3I5aFdCZE4zc29FY1RBQ0dqY0NVa0tWZy9WZHQxbDN4OW5qcWJiK1pud0JsYUNKcHloUkhSamEwdDY3XG42bHZsU2pJMURjR2hTUHZKWk5yZzJYOCtzeUUzc0xJR0pTdE00d3RoU3FES29pZ0IvQ3RhdExBSm5mNktuUHU3XG5MQjZwUjNlWFdrSDRtYlRQUzNrWXhxU1dcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay12MWlickB0ZXN0Mi03NGI4Mi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDg1MzM5MTc5OTM4NzAxNDM2MTIiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLXYxaWJyJTQwdGVzdDItNzRiODIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait
